FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

ARG VITE_API_BASE_URL
ARG VITE_BASE_URL
ARG VITE_MAP_API
ARG VITE_IMG_URL
ARG VITE_RAZORPAY_KEY_ID
ARG VITE_GET_GEOLOCATION

ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_BASE_URL=$VITE_BASE_URL
ENV VITE_MAP_API=$VITE_MAP_API
ENV VITE_IMG_URL=$VITE_IMG_URL
ENV VITE_RAZORPAY_KEY_ID=$VITE_RAZORPAY_KEY_ID
ENV VITE_GET_GEOLOCATION=$VITE_GET_GEOLOCATION

RUN npm run build

FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]