export const config = {
  VITE_API_BASE_URL: import.meta.env.VITE_API_BASE_URL,
  VITE_BASE_URL: import.meta.env.VITE_BASE_URL,
  VITE_MAP_API: import.meta.env.VITE_MAP_API,
  VITE_RAZORPAY_KEY_ID: "rzp_test_BuBQsRf6LPIv87",
  VITE_RAZORPAY_KEY_SECRET: import.meta.env.VITE_RAZORPAY_KEY_SECRET,
  VITE_GET_GEOLOCATION: import.meta.env.VITE_GET_GEOLOCATION,
  VITE_RAZORPAY_CHECKOUT_URL: import.meta.env.VITE_RAZORPAY_CHECKOUT_URL,
};
