import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
const RejectionModal = ({ isOpen, onclose, onConfirm, confirmText = "Confirm", cancelText = "Cancel", }) => {
    const [message, setMessage] = useState("");
    if (!isOpen)
        return null;
    const handleConfirm = () => {
        onConfirm(message);
        onclose();
    };
    return (_jsx("div", { className: "fixed inset-0 bg-black/40 bg-opacity-50 flex items-center justify-center z-50 p-4", children: _jsxs("div", { className: "bg-white rounded-lg shadow-xl max-w-md w-full mx-4", children: [_jsxs("div", { className: "flex items-center justify-between p-6 border-b border-gray-200", children: [_jsxs("div", { className: "flex items-center space-x-3", children: [_jsx("div", { className: "flex-shrink-0 w-10 h-10 bg-red-100 rounded-full flex items-center justify-center", children: _jsx("svg", { className: "w-6 h-6 text-red-600", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: "2", d: "M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L3.732 16.5c-.77.833.192 2.5 1.732 2.5z" }) }) }), _jsx("h3", { className: "text-lg font-semibold text-gray-900", children: "Rejection Reason" })] }), _jsx("button", { onClick: () => onclose(), className: "text-gray-400 hover:text-gray-600 transition-colors", children: _jsx("svg", { className: "w-6 h-6", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: "2", d: "M6 18L18 6M6 6l12 12" }) }) })] }), _jsxs("div", { className: "p-6 space-y-4", children: [_jsx("label", { htmlFor: "reason", className: "block text-sm font-medium text-gray-700 mb-2", children: "Reason" }), _jsx("textarea", { name: "reason", id: "reason", className: "w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-red-500 focus:border-red-500 resize-none h-24 text-sm placeholder-gray-400", placeholder: "Please provide a reason for rejection...", onChange: (e) => setMessage(e.target.value) })] }), _jsxs("div", { className: "flex justify-end space-x-3 px-6 py-4 bg-gray-50 rounded-b-lg", children: [_jsx("button", { onClick: () => onclose(), className: "px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 transition-colors", children: cancelText }), _jsx("button", { onClick: handleConfirm, disabled: !message, className: "px-4 py-2 text-sm font-medium text-white bg-red-600 border border-transparent rounded-md hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 transition-colors", children: confirmText })] })] }) }));
};
export default RejectionModal;
