import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ArrowRight, Play } from "lucide-react";
import { Button } from "../ui/button";
import { useNavigate } from "react-router-dom";
const PublicHeader = () => {
    const navigate = useNavigate();
    return (_jsx("section", { className: "w-full py-12 ", children: _jsx("div", { className: "container px-4 md:px-6", children: _jsxs("div", { className: "grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]", children: [_jsxs("div", { className: "flex flex-col justify-center space-y-4", children: [_jsxs("div", { className: "space-y-2", children: [_jsx("div", { className: "inline-block rounded-lg bg-muted px-3 py-1 text-sm", children: "Plan Your Next Escape" }), _jsx("h1", { className: "text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none", children: "Explore Unique Experiences Around the World" }), _jsx("p", { className: "max-w-[600px] text-muted-foreground md:text-xl", children: "From thrilling adventures to serene agro retreats and vibrant cultural tours \u2014 Global Explorer lets you discover and book unforgettable travel experiences in just a few clicks." })] }), _jsxs("div", { className: "flex flex-col gap-2 min-[400px]:flex-row", children: [_jsxs(Button, { size: "lg", className: "inline-flex items-center gap-2", onClick: () => navigate("/home"), children: ["Start Exploring", _jsx(ArrowRight, { className: "h-4 w-4" })] }), _jsxs(Button, { variant: "outline", size: "lg", className: "inline-flex items-center gap-2 bg-transparent", onClick: () => navigate("/login"), children: [_jsx(Play, { className: "h-4 w-4" }), "Login"] })] }), _jsxs("div", { className: "flex items-center space-x-4 text-sm text-muted-foreground", children: [_jsxs("div", { className: "flex items-center space-x-1", children: [_jsx("span", { children: "\u2713" }), _jsx("span", { children: "Instant booking \u2014 no hassle" })] }), _jsxs("div", { className: "flex items-center space-x-1", children: [_jsx("span", { children: "\u2713" }), _jsx("span", { children: "Handpicked tours & verified hosts" })] })] })] }), _jsx("div", { className: "flex items-center justify-center", children: _jsx("img", { src: "background/0bfe5acada1433436c816f79f1670ff3.jpg", width: "500", height: "500", alt: "Hero illustration", className: "mx-auto aspect-square overflow-hidden rounded-xl object-cover shadow-2xl" }) })] }) }) }));
};
export default PublicHeader;
