export interface User {
  _id: string,
  firstName: string,
  lastName: string,
  email: string,
  phoneNumber: string,
  role: string,
  isBlocked: boolean,
  password?: string,
  createAt: Date,
  updateAt: Date,
  token: string
}
export interface Host {
  _id: string,
  firstName: string,
  lastName: string,
  email: string,
  phoneNumber: string,
  role: string,
  isBlocked: boolean,
  password?: string,
  kyc_idProof: string,
  kyc_addressProof: string,
  kyc_panCard: string,
  kyc_verified: string,
  accountHolderName: string,
  accountNumber: string,
  ifsc: string,
  branch: string,
  registrationCertificate: string,
  safetyCertificate: string,
  license: string,
  insurance: string,
  isVerified: string,
  createdAt: Date,
  updatedAt: Date,
}

export interface AdminProfile {
  email: string;
  password?: string;
}

export interface Category {
  _id: string,
  categoryName: string,
  description: string,
  isActive: string,
  createdAt: string,
  updatedAt: string,
}

export interface Activity {
  _id: string;
  activityName: string;
  itenary: string;
  maxCapacity: number;
  categoryId: string;
  pricePerHead: number;
  userId: string;
  street: string;
  city: string;
  district: string;
  state: string;
  postalCode: string;
  country: string;
  recurrenceDays: [string];
  location: {
    type?: string;
    coordinates: [number, number];
  };
  images: (string | File)[];
  reportingPlace: string;
  reportingTime: string;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
  //-----
  basePrice: number;
  dynamicPricingEnabled: boolean;
  maxDynamicPercentage: number;
  offerPercentage: number;
}

export interface Review {
  _id: string;
  entityId: string;
  userId: string | {
    _id: string;
    firstName: string;
    lastName: string;
  }
  rating: number;
  title: string;
  comment: string;
  createdAt: string;
  updatedAt: string;
}

export interface BlogPost {
  _id: string;            // MongoDB ObjectId as a string
  userId: string;         // Author's user ID
  title: string;          // Blog title
  author: string;         // Author name (redundant but useful for fast access)
  introduction: string;   // Short intro or preview text
  sections: BlogSection[]; // Multiple sections in the blog
  image: string ;          // Main or introduction image
  views: number;          // Number of views
  likes: string[];        // Array of userIds who liked it
  createdAt: Date;        // Auto-generated by MongoDB or backend
  updatedAt: Date;        // Auto-updated on edits
}

export interface BlogSection {
  sectionTitle: string;        // Title of the section
  content: string;        // Body content (Markdown or HTML)
  image?: string ;         // Optional image for the section
}


export interface Booking {
  _id: string;
  userId: string;
  activityId: string;
  activityTitle: string;
  date: string;
  participantCount: number;
  pricePerParticipant: number;
  paymentStatus: "pending" | "paid" | "failed" | "refunded";
  razorpayPaymentId?: string;
  razorpayOrderId?: string;
  razorpaySignatue?: string;
  qrCode: string;
  qrToken: string;
  bookingStatus: "pending" | "cancelled" | "completed";
  hostId: string;
  isCancelled: boolean;
  cancellationReason?: string;
  isRefunded: boolean;
  refundId?: string;
  refundAmount?: number;
  refundStatus?: "initialized" | "completed" | "failed";
  razorpayTransferId?: string;
  isReleasedId: boolean;
  holdUntilDate: string;
  updatedAt: string;
  createdAt: string;
}

export interface Message {
  _id: string;
  conversationId?: string | ObjectId;
  senderId: string;
  receiverId?: string;
  content: string;
  read: boolean;
  sentAt: string;
}

export interface Conversation {
  _id: string;
  participants: string[];
  lastMessage: string;
  lastSender: string;
  lastMessageAt: string;
  unreadCount: Record<string, number>
}

export interface ConversationResponse extends Conversation {
  receiverId: string;
  firstName: string;
  lastName: string;
}

export interface SearchUsers {
  _id: string;
  firstName: string;
  lastName: string;
}

export interface Notification {
  _id: string;
  userId: string;
  type: string;
  message: string;
  isRead: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface DashboardData {
  _id: string,
  count: number,
  totalParticipants: number,
  activity: {
    activityName: string,
    pricePerHead: number,
  }
  category: {
    categoryName: string,
  }
}

export interface SalesData {
  current: { _id: { month: number }; totalSales: number; count: number }[];
  previous: { _id: { month: number }; totalSales: number; count: number }[],
}

export interface Review {
  _id: string;
  entityId: string;
  userId: string;
  title: string;
  comment: string;
  rating: number;
  createdAt: string;
  updatedAt: string;
}

export interface ActivityData {
  activityId: string;
  activityName: string;
  availability: Array<{
    date: string;
    availableSeats: number;
    totalSeats: number;
    bookedSeats: number;
  }>;
}
 
export interface AuthResponse {
  user?: User | Host | null | undefined,
  category?: Category 
  categories?: Category[]
  activities?: Activity[] ,
  blogs?: BlogPost[],
  blog?: BlogPost,
  images?: GalleryImages[],
  activity?: Activity
  reviews?: Review[]
  totalPages?: number,
  unreadCount?: number,
  razorpayAccountId?: string,
  availabilities?: Availability[],
  availability?: {date: string, availableSeats: number}[]
  availableSlots?: ActivityData[];
  booking?: Booking,
  bookings?: Booking[] | BookingWithUser[],
  bookingsWithUser?: BookingWithUser[];
  conversations?: ConversationResponse [],
  conversation?: Conversation,
  messages?: Message[],
  userSearch?: SearchUsers[],
  notifications?: Notification,
  notification?: Notification,
  userCount?: number,
  hostCount?: number,
  activityCount?:number,
  bookingCount?: number,
  upCommingBooking?: number,
  cancelledBooking?: number,
  completedBooking?: number,
  monthlyBookings?: {
      _id: { month: number };
      count: number;
    }[]
  dashboardData?: DashboardData[],
  salesData?: SalesData,
  review?: Review,
  token?: string | null | undefined;
  message?: string;
}
export interface ResponseType<T> {
  data: T;
  status: number;
  statusText?: string;
  headers?: Record<string,string>;
  config?: {
    url?: string;
    method?: string;
  };
  request?: unknown;
}

export type ChildrenProps = {
    children: React.ReactNode
}

export type GalleryImages = {
    image: string;
    title: string;
    _id: string;
    url: string;
  }

export interface BookingWithUser extends Booking {
  user: Omit<User, "password">;
}

export type DateFilterType = "single" | "today" | "yesterday" | "range" | "week" | "month" | "year" | "all"

export interface SalesFilters {
  dateFilterType: DateFilterType
  fromDate?: string // ISO string
  toDate?: string // ISO string
  minPrice?: number
  maxPrice?: number
}

export interface Availability {
  _id: string;
  date: string;
  activityId: string;
  availableSeats: number;
  totalSeats: number;
  createdAt: string;
  updatedAt: string;
}